### ISSUE TITLE
Graphical environment needed to use it in command line

### ISSUE THREAD

**Issue by junming** [TomasoAlbinoni/Trados-Studio-Resource-Converter#1]
Hi Tomaso,

When running on a headless server Linux I get:

$ java -jar TradosStudioResourceConverter.jar
Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
        at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
        at java.awt.Window.<init>(Window.java:536)
        at java.awt.Frame.<init>(Frame.java:420)
        at javax.swing.JFrame.<init>(JFrame.java:233)
        at sdlconverter.SDLConverter.<clinit>(SDLConverter.java:225)

Could you please remove references to a display in the code? I see that it can be run fine on Windows (where I run it from time to time) but because of the current limitations there is no possibility to run it without a display engine on Linux. As it's mentioned on the page http://www.vannellen.com/fortranslators.php that:

"Can I use the converter from the command line?

Yes, but at this time only to convert .sdltm files:"

And this is precisely what I am trying to do. It would be great if I could do it on a server. Thanks!! :)

**Comment by TomasoAlbinoni** [comment]
Hi junming,

Thanks for flagging this. I may do something about it when I have some free time. Meanwhile feel free to fork.

Thomas

**Comment by junming** [comment]
Thanks Thomas,
If I knew Java I would, but unfortunately this is one of the languages I
know nothing about... Let's hope someone else can help, I will look for an
alternative in the meantime. Thanks and keep up the good work!

Le lun. 23 janv. 2017 18:40, Thomas van Nellen <notifications@github.com> a
écrit :
